image: artifactory.global.dish.com/wireless-docker-dev-local/dish-wireless-cicd-build-tools:v0.1

variables:
  EKS_CLUSTER_NAME: "hansen-pi-dev"
  ACCOUNT_ID: "227453601360"
  REGION: "us-west-2"

stages:
  - Terraform-Creation
#  - Create-Kubernetes-Secrets-DEV

build:                     
  stage: Terraform-Creation 
  image: artifactory.global.dish.com/sling/hashi:master     
  tags:                         
    - wireless-grouprunner-cicd
  script:
    - ls -la
    - export AWS_DEFAULT_REGION
    - AWS_STS_REGIONAL_ENDPOINTS=regional
    - export AWS_STS_REGIONAL_ENDPOINTS  
    - aws sts get-caller-identity --endpoint-url $epurl
    - json_out=$(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/Gitlab-Runner-Executor-Role --role-session-name "$session_name" --endpoint-url $epurl)
    - aws_access_key_id=$(echo "$json_out" | jq -r ".Credentials.AccessKeyId")
    - aws_secret_access_key=$(echo "$json_out" | jq -r ".Credentials.SecretAccessKey")
    - aws_session_token=$(echo "$json_out" | jq -r ".Credentials.SessionToken")
    - export AWS_ACCESS_KEY_ID="$aws_access_key_id"
    - export AWS_SECRET_ACCESS_KEY="$aws_secret_access_key"
    - export AWS_SESSION_TOKEN="$aws_session_token"
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $AWS_SESSION_TOKEN
   # - chmod -R 777 .terraform/plugins/linux_amd64/terraform-provider-aws_v3.55.0_x5
   # - terraform init -plugin-dir .terraform/plugins/linux_amd64
    - git clone https://gitlab.global.dish.com/it-wireless-commercial-application-engineering-repos/centralized-deployment-automation/terraform_plugin_provider.git
    - ls -la
    - mv terraform_plugin_provider .terraform_plugin_provider
    - chmod -R 777 .terraform_plugin_provider/*
    - terraform init -plugin-dir .terraform_plugin_provider
    - terraform validate
    # - export TF_LOG=TRACE
    - terraform plan -input=false
    - terraform apply -auto-approve -input=false
    
#create-secrets-kubernetes-dev:
#  stage: Create-Kubernetes-Secrets-DEV
#  image: artifactory.global.dish.com/wireless-docker-dev-local/dish-wireless-cicd-build-tools:v0.1
#  tags:
#    - wireless-grouprunner-cicd
#  script:
#    - export AWS_DEFAULT_REGION
#    - AWS_STS_REGIONAL_ENDPOINTS=regional
#    - export AWS_STS_REGIONAL_ENDPOINTS  
#    - aws sts get-caller-identity --endpoint-url $epurl
#    - json_out=$(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/Gitlab-Runner-Executor-Role --role-session-name "$session_name" --endpoint-url $epurl)
#    - aws_access_key_id=$(echo "$json_out" | jq -r ".Credentials.AccessKeyId")
#    - aws_secret_access_key=$(echo "$json_out" | jq -r ".Credentials.SecretAccessKey")
#    - aws_session_token=$(echo "$json_out" | jq -r ".Credentials.SessionToken")
#    - export AWS_ACCESS_KEY_ID="$aws_access_key_id"
#    - export AWS_SECRET_ACCESS_KEY="$aws_secret_access_key"
#    - export AWS_SESSION_TOKEN="$aws_session_token"
#    - aws eks update-kubeconfig --region us-west-2 --name $EKS_CLUSTER_NAME
#    - kubectl create secret generic mongo-sc --from-literal=username=$MONGO_USER --from-literal=password=$MONGO_PASSWORD -n hansen-pi
#    - kubectl create secret generic keystore-sc --from-literal=password=$KEY_PASSWORD -n hansen-pi
#    - kubectl create secret generic truststore-sc --from-literal=password=$TRUST_PASSWORD -n hansen-pi
